# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json

version: 2

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

before:
  hooks:
    - go mod tidy
    - rm -rf completions
    - mkdir completions
    - rm -rf manpages
    - mkdir manpages
    - sh -c 'go run . completion bash >./completions/glow.bash'
    - sh -c 'go run . completion zsh >./completions/glow.zsh'
    - sh -c 'go run . completion fish >./completions/glow.fish'
    - sh -c 'go run . man | gzip -c >./manpages/glow.1.gz'

builds:
  - binary: glow
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.Version={{ .Version }}
      - -X main.CommitSHA={{ .Commit }}
      - -X main.CommitDate={{ .CommitDate }}
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format_overrides:
      - goos: windows
        formats: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    files:
      - README*
      - LICENSE*
      - manpages/*
      - completions/*

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
